#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v21
# autospec commit: 542402611043
#
Name     : bpftool
Version  : 7.5.0
Release  : 2
URL      : https://github.com/libbpf/bpftool/releases/download/v7.5.0/bpftool-libbpf-v7.5.0-sources.tar.gz
Source0  : https://github.com/libbpf/bpftool/releases/download/v7.5.0/bpftool-libbpf-v7.5.0-sources.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0 LGPL-2.1
Requires: bpftool-bin = %{version}-%{release}
Requires: bpftool-license = %{version}-%{release}
BuildRequires : elfutils-dev
BuildRequires : pkgconfig(libelf)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-build-install-toplevel-Makefile.patch

%description
<a href=".github/assets/">
<div>
<img src=".github/assets/bpftool_horizontal_color.svg"
alt="bpftool logo: Hannah the Honeyguide"
width=500px; />
</div>
</a>

%package bin
Summary: bin components for the bpftool package.
Group: Binaries
Requires: bpftool-license = %{version}-%{release}

%description bin
bin components for the bpftool package.


%package license
Summary: license components for the bpftool package.
Group: Default

%description license
license components for the bpftool package.


%prep
%setup -q -n bpftool-libbpf-v7.5.0-sources
cd %{_builddir}/bpftool-libbpf-v7.5.0-sources
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1731631211
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1731631211
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bpftool
cp %{_builddir}/bpftool-libbpf-v%{version}-sources/LICENSE %{buildroot}/usr/share/package-licenses/bpftool/1a8626fdd1a6f6399717f401588a171fd99b2f5d || :
cp %{_builddir}/bpftool-libbpf-v%{version}-sources/LICENSE.BSD-2-Clause %{buildroot}/usr/share/package-licenses/bpftool/34c5034377edef1080538bd0d4f5cf9b78e22dff || :
cp %{_builddir}/bpftool-libbpf-v%{version}-sources/LICENSE.GPL-2.0 %{buildroot}/usr/share/package-licenses/bpftool/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/bpftool-libbpf-v%{version}-sources/libbpf/LICENSE.BSD-2-Clause %{buildroot}/usr/share/package-licenses/bpftool/419ec3c0b11c7d22472ea99c03c347413a4ea406 || :
cp %{_builddir}/bpftool-libbpf-v%{version}-sources/libbpf/LICENSE.LGPL-2.1 %{buildroot}/usr/share/package-licenses/bpftool/91c66db733cf0ff2b3216ec4223b940daf6b26d4 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bpftool

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bpftool/1a8626fdd1a6f6399717f401588a171fd99b2f5d
/usr/share/package-licenses/bpftool/34c5034377edef1080538bd0d4f5cf9b78e22dff
/usr/share/package-licenses/bpftool/419ec3c0b11c7d22472ea99c03c347413a4ea406
/usr/share/package-licenses/bpftool/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/bpftool/91c66db733cf0ff2b3216ec4223b940daf6b26d4
